added link to the dedicated discord
elocnatsirt/indieracers.com pull request #5
Opened 2022-07-30 16:36 UTC by zugolbr

Thanks again! :)

2022-07-30 17:46 UTC, elocnatsirt requested changes

2022-07-30 17:46 UTC, elocnatsirt commented on index.html
> +            <a target="_blank" href="https://forms.gle/h8cJfu1m3dtK4b1e6">DEDICATED DISCORD</a> (PLAYERS + STREAMERS)
Wrong link, should be Discord invite link!

2022-07-31 09:29 UTC, zugolbr reviewed
Thanks for watching out! ;)

2022-07-31 14:53 UTC, elocnatsirt approved these changes

2022-07-31 14:53 UTC, merged